<div id="header-bottom-wrap" class="is-clearfix">
        <div id="header-bottom" class="site-header-bottom">
          <div id="header-bottom-inner" class="site-header-bottom-inner ">
            <section class="hero page-title is-medium has-text-centered about">
              <div class="hero-body">
                <div class="container">
                  <h1>Über uns</h1>
                  <h3>EU-TRUCKERS – EWP MARKE</h3>
                </div>
                <!-- .hero-body -->
              </div>
              <!-- .container -->
            </section>
            <!-- .page-title -->
          </div>
          <!-- #header-bottom-inner -->
        </div>
        <!-- #header-bottom -->
      </div>

      <div id="content-main-wrap" class="is-clearfix">
              <div id="content-area" class="site-content-area">
                <div id="content-area-inner" class="site-content-area-inner">
                  <section class="section introduction is-clearfix">
                    <div class="container">
                      <p class="heading-title-top has-text-centered">EU-TRUCKERS EINE MARKE EWP</p>
                      <h1 class="heading-title style-3">European Work Power</h1>
                      <p class="has-text-centered">EWP ist aus dem Wunsch heraus entstanden, Chancengleichheit für alle Fachkräfte in der Europäischen Union zu schaffen,
unabhängig von ihrer Qualifikation. Wir haben unsere Zeit und Anstrengungen darauf verwendet, einen schnellen Prozess der
Platzierung auf dem Arbeitsmarkt zu schaffen, wodurch der Aufwand und die kostspielige Zeit für alle unsere Kunden minimiert werden.

Wir glauben an die Kraft einer schnellen und effizienten Kommunikation, an Transparenz, wenn wir über Rechte und Pflichten
sprechen, und insbesondere an die Möglichkeiten, die uns die aktuelle Technologie bietet. Das gesamte EWP-Team wächst
ständig und wird sich auf die Umsetzung der Vision konzentrieren, starke und dauerhafte Verbindungen zwischen Bewerbern und Arbeitgebern aufzubauen.</p>
                      <br>
                      <br>
                      <br>
                    </div>
                  </section>


                  <section id="testimonials" class="section testimonials-section has-background-primary-light is-clearfix">
                  <div class="container">
          <p class="heading-title-top has-text-centered">Bewertungen</p>
          <h1 class="heading-title style-3">Ein Teil unserer Bewertungen</h1>
          <div class="testimonials  owl-carousel dots carousel-items-3 columns-style-1 ">
            <div class="testimonials-item">
              <p>„Ein Unternehmen, das die Bedürfnisse der Fahrer aus allen Blickwinkeln wirklich versteht. Zögern Sie also nicht, sich zu bewerben. Sehr zu empfehlen!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100005792053981/picture?type=large">
              <h3>Adrian Titus
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Ein Unternehmen, das auf die Bedürfnisse der Fahrer eingeht.</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100000878227676/picture?type=large">
              <h3>Dan Floruta
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>„Ich empfehle mit allem Vertrauen! Ein seriöses Unternehmen, das die Bedürfnisse seiner Kunden berücksichtigt“</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100002437091632/picture?type=large">
              <h3>Enache Alexandru
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Empfehlung mit Vertrauen, ich bin in jeder Hinsicht sehr zufrieden.</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100025031414151/picture?type=large">
              <h3>Dumitru Coroiu
                <br>
                <span>Facebook</span>
              </h3>
            </div>
          </div>
        </div>
      </section>

                  <section class="section  is-clearfix">
                    <div class="container">
                      <nav class="level counterup ">
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">6844</p>
                            <p class="heading">Bearbeitete Kandidaten</p>
                          </div>
                        </div>
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">1034</p>
                            <p class="heading">Kooperierende Unternehmen</p>
                          </div>
                        </div>
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">4149</p>
                            <p class="heading">Platzierungen im letzten Jahr</p>
                          </div>
                        </div>
                      </nav>
                      <!-- .counterup -->
                    </div>
                  </section>

                </div>
                <!-- #content-area-inner -->
              </div>
              <!-- #content-area -->
            </div>
