<div id="header-bottom-wrap" class="is-clearfix">
        <div id="header-bottom" class="site-header-bottom">
          <div id="header-bottom-inner" class="site-header-bottom-inner ">
            <section class="hero page-title is-medium has-text-centered about">
              <div class="hero-body">
                <div class="container">
                  <h1>About us</h1>
                  <h3>EU-TRUCKERS - EWP BRAND</h3>
                </div>
                <!-- .hero-body -->
              </div>
              <!-- .container -->
            </section>
            <!-- .page-title -->
          </div>
          <!-- #header-bottom-inner -->
        </div>
        <!-- #header-bottom -->
      </div>

      <div id="content-main-wrap" class="is-clearfix">
              <div id="content-area" class="site-content-area">
                <div id="content-area-inner" class="site-content-area-inner">
                  <section class="section introduction is-clearfix">
                    <div class="container">
                      <p class="heading-title-top has-text-centered">EU-TRUCKERS un brand</p>
                      <h1 class="heading-title style-3">European Work Power</h1>
                      <p class="has-text-centered">EWP has emerged from the desire to create equal opportunities and opportunities for all professionals in the European Union, regardless of their qualifications. We have dedicated our time and efforts to create a quick process of placing on the labor market, minimizing the efforts and costly time for all our clients.
We believe in the power of fast and efficient communication, in transparency when we talk about rights and obligations and especially in the opportunities that current technology offers us. The entire EWP team is constantly growing and will focus its efforts on implementing the vision to build strong and lasting connections between candidates and employers.</p>
                      <br>
                      <br>
                      <br>
                    </div>
                  </section>


                  <section id="testimonials" class="section testimonials-section has-background-primary-light is-clearfix">
        <div class="container">
          <p class="heading-title-top has-text-centered">reviews</p>
          <h1 class="heading-title style-3">Our Reviews</h1>
          <div class="testimonials  owl-carousel dots carousel-items-3 columns-style-1 ">
            <div class="testimonials-item">
              <p>O companie care intr-adevar intelege nevoile soferilor din toate punctele de vedere, asa ca nu ezitati sa aplicati.<br>
Recomand cu mare incredere!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100005792053981/picture?type=large">
              <h3>Adrian Titus
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>O companie care se gandeste la nevoile soferilor!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100000878227676/picture?type=large">
              <h3>Dan Floruta
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Recomand cu toată încrederea! Firmă serioasă care ține cont de nevoile clienților.</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100002437091632/picture?type=large">
              <h3>Enache Alexandru
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Recomand cu incredere eu sînt foarte multumit din toate punctele de vedere</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100025031414151/picture?type=large">
              <h3>Dumitru Coroiu
                <br>
                <span>Facebook</span>
              </h3>
            </div>
          </div>
        </div>
      </section>

                  <section class="section  is-clearfix">
                    <div class="container">
                      <nav class="level counterup ">
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">6844</p>
                            <p class="heading">Processed candidates</p>
                          </div>
                        </div>
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">1034</p>
                            <p class="heading">Partner companies</p>
                          </div>
                        </div>
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">4149</p>
                            <p class="heading">Placements in the last year</p>
                          </div>
                        </div>
                      </nav>
                      <!-- .counterup -->
                    </div>
                  </section>

                </div>
                <!-- #content-area-inner -->
              </div>
              <!-- #content-area -->
            </div>
