<div id="header-bottom-wrap" class="is-clearfix">
        <div id="header-bottom" class="site-header-bottom">
          <div id="header-bottom-inner" class="site-header-bottom-inner ">
            <section class="hero page-title is-medium has-text-centered about">
              <div class="hero-body">
                <div class="container">
                  <h1>Despre noi</h1>
                  <h3>EU-TRUCKERS - EWP BRAND</h3>
                </div>
                <!-- .hero-body -->
              </div>
              <!-- .container -->
            </section>
            <!-- .page-title -->
          </div>
          <!-- #header-bottom-inner -->
        </div>
        <!-- #header-bottom -->
      </div>

      <div id="content-main-wrap" class="is-clearfix">
              <div id="content-area" class="site-content-area">
                <div id="content-area-inner" class="site-content-area-inner">
                  <section class="section introduction is-clearfix">
                    <div class="container">
                      <p class="heading-title-top has-text-centered">EU-TRUCKERS un brand</p>
                      <h1 class="heading-title style-3">European Work Power</h1>
                      <p class="has-text-centered">EWP a aparut din dorinta de a crea egalitate de sanse si oportunitati tuturor profesionistilor din cadrul Uniunii Europene indiferent de calificarea avuta. Ne-am dedicat timpul si eforturile pentru a crea un process rapid de plasare pe piata muncii, minimalizand eforturile si timpul costisitor pentru toti clientii nostrii.<br>
Credem in puterea comunicarii rapide si eficiente, in transparenta atunci cand vorbim de drepturi si obligatii si mai ales in oportunitatile pe care tehnologia currenta ni le pune la dispozitie.
 Intreaga echipa EWP  se afla in continua crestere si isi va concentra eforturile pentru implementarea viziunii de a construi legaturi puternice si de durata intre candidati si angajatori.</p>
                      <br>
                      <br>
                      <br>
                    </div>
                  </section>


                  <section id="testimonials" class="section testimonials-section has-background-primary-light is-clearfix">
        <div class="container">
          <p class="heading-title-top has-text-centered">recenzii</p>
          <h1 class="heading-title style-3">o parte din recenziile noastre</h1>
          <div class="testimonials  owl-carousel dots carousel-items-3 columns-style-1 ">
            <div class="testimonials-item">
              <p>O companie care intr-adevar intelege nevoile soferilor din toate punctele de vedere, asa ca nu ezitati sa aplicati.<br>
Recomand cu mare incredere!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100005792053981/picture?type=large">
              <h3>Adrian Titus
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>O companie care se gandeste la nevoile soferilor!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100000878227676/picture?type=large">
              <h3>Dan Floruta
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Recomand cu toată încrederea! Firmă serioasă care ține cont de nevoile clienților.</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100002437091632/picture?type=large">
              <h3>Enache Alexandru
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Recomand cu incredere eu sînt foarte multumit din toate punctele de vedere</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100025031414151/picture?type=large">
              <h3>Dumitru Coroiu
                <br>
                <span>Facebook</span>
              </h3>
            </div>
          </div>
        </div>
      </section>

                  <section class="section  is-clearfix">
                    <div class="container">
                      <nav class="level counterup ">
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">6844</p>
                            <p class="heading">Candidati procesati</p>
                          </div>
                        </div>
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">1034</p>
                            <p class="heading">Firme in colaborare</p>
                          </div>
                        </div>
                        <div class="level-item has-text-centered">
                          <div>
                            <p class="title counter">4149</p>
                            <p class="heading">Plasari efectuate in ultimul an</p>
                          </div>
                        </div>
                      </nav>
                      <!-- .counterup -->
                    </div>
                  </section>

                </div>
                <!-- #content-area-inner -->
              </div>
              <!-- #content-area -->
            </div>
