<div id="header-bottom-wrap" class="is-clearfix">
        <div id="header-bottom" class="site-header-bottom">
          <div id="header-bottom-inner" class="site-header-bottom-inner ">
            <section class="hero page-title is-medium has-text-centered contact">
              <div class="hero-body">
                <div class="container">
                  <h1>Contacteaza-ne</h1>
                  <h3>Suntem la dispozitia ta.</h3>
                </div>
                <!-- .hero-body -->
              </div>
              <!-- .container -->
            </section>
            <!-- .page-title -->
          </div>
          <!-- #header-bottom-inner -->
        </div>
        <!-- #header-bottom -->
      </div>

      <div id="content-main-wrap" class="is-clearfix">
        <div id="content-area" class="site-content-area">
          <div id="content-area-inner" class="site-content-area-inner">
            <!-- contact-form section -->
            <section class="section contact-form is-clearfix">
              <div class="container">
                <p class="heading-title-top has-text-centered">Ne poti contacta mai jos</p>
                <h1 class="heading-title style-3">Cum te putem ajuta?</h1>
                <div class="has-text-centered">
                  <div class="global-social-links style-1">
                    <ul>
                      <li>
                        <a href="https://facebook.com/EuTruckers/">
                          <span class="icon">
                            <i class="fab fa-facebook-f"></i>
                          </span>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
                <br>
                <br>
                <br>
                <br>
                <div class="columns is-multiline is-variable is-8">
                  <div class="column is-4">
                    <div class="columns is-variable is-4 is-multiline boxes-style-3">
                      <div class="column is-12 aos-init aos-animate" data-aos="fade">
                        <div class="box-item media">
                          <div class="media-left">
                            <a href="../pages/contact.html">
                              <span class="icon">
                                <i class="ion-ios-pin-outline"></i>
                              </span>
                            </a>
                          </div>
                          <div class="media-content">
                            <h3>
                              <a href="../pages/contact.html">Adresa</a>
                            </h3>
                            <p>Str. Surul 9 C, Sibiu, Romania</p>
                          </div>
                        </div>
                        <!-- .box-item -->
                      </div>
                      <div class="column is-12 aos-init" data-aos="fade">
                        <div class="box-item media">
                          <div class="media-left">
                            <a href="../pages/contact.html">
                              <span class="icon">
                                <i class="ion-ios-call-outline"></i>
                              </span>
                            </a>
                          </div>
                          <div class="media-content">
                            <h3>
                              <a href="../pages/contact.html">Telefon</a>
                            </h3>
                            <p>+40 735 183 011</p>
                          </div>
                        </div>
                        <!-- .box-item -->
                      </div>
                      <div class="column is-12 aos-init" data-aos="fade">
                        <div class="box-item media">
                          <div class="media-left">
                            <a href="../pages/contact.html">
                              <span class="icon">
                                <i class="ion-ios-mail-outline"></i>
                              </span>
                            </a>
                          </div>
                          <div class="media-content">
                            <h3>
                              <a href="../pages/contact.html">Email</a>
                            </h3>
                            <p>contact@eu-truckers.com</p>
                          </div>
                        </div>
                        <!-- .box-item -->
                      </div>
                    </div>
                    <!-- .columns -->
                  </div>
                  <div class="column is-8">
                    <!-- successful form message -->
                    <div class="overhang-message-content is-hidden success">
                      <span class="icon">
                        <i class="ion-md-notifications"></i>
                      </span> Thank You! Your message was sent successfully. </div>
                    <!-- error form message -->
                    <div class="overhang-message-content is-hidden error">
                      <span class="icon">
                        <i class="ion-md-notifications"></i>
                      </span> Oops! Something went wrong, we couldn't send your message. </div>
                    <!-- ajax contact form -->
                    <form accept-charset="UTF-8" class="ajax-contact-form" action="https://usebasin.com/f/3587049dbc33.json" method="POST">
                      <div class="field is-horizontal">
                        <div class="field-body">
                          <div class="field">
                            <div class="control is-expanded">
                              <input class="input" type="text" name="name" placeholder="Numele tau complet" required=""> </div>
                          </div>
                          <!-- .field -->
                          <div class="field"> 
                            <div class="control is-expanded">
                              <input class="input" type="text" name="subject" placeholder="Subiect" required=""> </div>
                          </div>
                          <!-- .field -->
                        </div>
                        <!-- .field-body -->
                      </div>
                      <!-- .field -->
                      <div class="field is-horizontal">
                        <div class="field-body">
                          <div class="field">
                            <div class="control is-expanded">
                              <input class="input" type="tel" name="phone" placeholder="Numarul tau de telefon" required=""> </div>
                          </div>
                          <!-- .field -->
                          <div class="field">
                            <div class="control is-expanded">
                              <input class="input" type="email" name="email" placeholder="Email-ul tau" required=""> </div>
                          </div>
                          <!-- .field -->
                        </div>
                        <!-- .field-body -->
                      </div>
                      <!-- .field -->
                      <div class="field ">
                        <div class="control is-expanded">
                          <textarea class="textarea" name="textarea" placeholder="Mesajul tau" required=""></textarea>
                        </div>
                      </div>
                      <!-- .field -->
                      <div class="field ">
                        <div class="control has-text-centered">
                          <button class="button" type="submit">Trimite mesaj</button>
                        </div>
                      </div>
                      <!-- .field -->
                    </form>
                  </div>
                </div>
                <br> </div>
            </section>
            <!-- .contact-form -->
          </div>
          <!-- #content-area-inner -->
        </div>
        <!-- #content-area -->
      </div>
