<?php 
global $app_url;
?>
<html>
<head>
<title>Form EU-TRUCKERS</title>

<link href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.4/semantic.min.css" rel="stylesheet" type="text/css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/css/intlTelInput.css" rel="stylesheet" type="text/css">
<style>
.iti--allow-dropdown{
    width: 100% !important;
}
</style>
</head>
<body>

<form id="formular" class="ui form has-validation-callback" target="formi" action="<?= $app_url;?>/en/thank-you" method="post">
                        <div class="ui two column grid">
                            <div class="column">

                                <div class="field">
                                    <label>Name </label>
                                    <input type="text" name="first_name" placeholder="Name" data-validation-error-msg="Please write your name" data-validation="length" data-validation-length="min3">
                                </div>
                                <div class="field">
                                    <label>Surname</label>
                                    <input type="text" name="last_name" placeholder="Surname" data-validation-error-msg="Please write your surname" data-validation="length" data-validation-length="min3">
                                </div>
                                <div class="field">
                                    <label>Phone</label>
                                    <input id="phone" type="tel" name="phones" placeholder="Telefon">
                                </div>
                                 <div class="field">
                                    <label>Email</label>
                                    <input type="text" name="email" placeholder="Email">
                                </div>

                                 <div class="field">
                                    <label>Are you available for relocating to Germany?</label>
                                    <div class="ui form">
                                      <div class="grouped fields">
                                        <div class="field">
                                          <div class="ui radio checkbox">
                                            <input type="radio" name="relocation" value="1">
                                            <label>Yes</label>
                                          </div>
                                        </div>
                                        <div class="field">
                                          <div class="ui radio checkbox">
                                            <input type="radio" name="relocation" value="0">
                                            <label>No</label>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                </div>

                                <div class="ui form">
                                    <div class="field">
                                    <label>Foreign known languages</label>
                                    <div class="field">
                                      <label>English</label>
                                      <div class="ui selection dropdown" tabindex="0">
                                          <input type="hidden" name="english">
                                          <i class="dropdown icon"></i>
                                          <div class="default text">English</div>
                                          <div class="menu" tabindex="-1">
                                              <div class="item" data-value="1">Begginer</div>
                                              <div class="item" data-value="2">Medium</div>
                                              <div class="item" data-value="3">Advanced</div>
                                          </div>
                                      </div>
                                    </div>
                                    <div class="field">
                                      <label>German</label>
                                      <div class="ui selection dropdown" tabindex="0">
                                          <input type="hidden" name="german">
                                          <i class="dropdown icon"></i>
                                          <div class="default text">German</div>
                                          <div class="menu" tabindex="-1">
                                              <div class="item" data-value="1">Begginer</div>
                                              <div class="item" data-value="2">Medium</div>
                                              <div class="item" data-value="3">Advanced</div>
                                          </div>
                                      </div>
                                    </div>
                                    <div class="field">
                                      <label>Italian</label>
                                      <div class="ui selection dropdown" tabindex="0">
                                          <input type="hidden" name="italian">
                                          <i class="dropdown icon"></i>
                                          <div class="default text">Italian</div>
                                          <div class="menu" tabindex="-1">
                                              <div class="item" data-value="1">Begginer</div>
                                              <div class="item" data-value="2">Medium</div>
                                              <div class="item" data-value="3">Advanced</div>
                                          </div>
                                      </div>
                                    </div>
                                    <div class="field">
                                      <label>French</label>
                                      <div class="ui selection dropdown" tabindex="0">
                                          <input type="hidden" name="french">
                                          <i class="dropdown icon"></i>
                                          <div class="default text">French</div>
                                          <div class="menu" tabindex="-1">
                                              <div class="item" data-value="1">Begginer</div>
                                              <div class="item" data-value="2">Medium</div>
                                              <div class="item" data-value="3">Advanced</div>
                                          </div>
                                      </div>
                                    </div>
                                    </div>
                                </div>


                            </div>
                            <div class="column">

                                <div class="field">
                                    <label>ADR</label>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="adr_collets" value="1"><label>Packaged Goods ADR</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="adr_cistern" value="1"><label> ADR Tank</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="adr_general" value="1"><label>General goods ADR</label>
                                    </div>
                                </div>

                                <div class="field">
                                    <label>Experience</label>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="experience_1" value="1"><label>Tarp Truck</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="experience_2" value="1"><label>Tank Truck</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="experience_3" value="1"><label>Container Truck</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="experience_4" value="1"><label>Tandem Truck</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="experience_5" value="1"><label>Refrigerator Truck</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="experience_6" value="1"><label>5 wheel Truck</label>
                                    </div>
                                </div>
                                <div class="field">
                                    <label>Driving distances</label>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="drives_1" value="1"><label>Long distance</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="drives_2" value="1"><label>Short distance</label>
                                    </div>
                                </div>

                                <div class="field">
                                    <label>Experience</label>
                                    <div class="ui form">
                                      <div class="grouped fields">
                                        <div class="field">
                                          <div class="ui radio checkbox">
                                            <input type="radio" name="driver_experience" value="1">
                                            <label>Beginner</label>
                                          </div>
                                        </div>
                                        <div class="field">
                                          <div class="ui radio checkbox">
                                            <input type="radio" name="driver_experience" value="2">
                                            <label>More than 1 year experience</label>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                </div>

                                <div class="field">
                                    <label>Accomodation</label>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="accommodation_1" value="1"><label> Living container paid by the employer</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="accommodation_2" value="1"><label> In the cabin</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="accommodation_3" value="1"><label> Living supported by you</label>
                                    </div>
                                </div>
                                <div class="field">
                                    <label>What type of driver licence do you posses?</label>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_1" value="1"><label>B</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_2" value="1"><label>C</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_3" value="1"><label>C1E</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_4" value="1"><label>CE</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_5" value="1"><label>D</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_7" value="1"><label>D1</label>
                                    </div>
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="license_6" value="1"><label>DE</label>
                                    </div>

                                </div>
                                <div class="field">
                                    <label>Expected salary (net in hand- euro)</label>
                                    <input type="text" name="salary">
                                </div>
                                <div class="field">
                                      <label>Availability</label>
                                      <div class="ui selection dropdown" tabindex="0">
                                          <input type="hidden" name="disponibility">
                                          <i class="dropdown icon"></i>
                                          <div class="default text">Availability</div>
                                          <div class="menu" tabindex="-1">
                                              <div class="item" data-value="1">Immediately</div>
                                              <div class="item" data-value="2">1-2 weeks</div>
                                              <div class="item" data-value="3">1 month</div>
                                          </div>
                                      </div>
                                    </div>

                                    <div class="column">
                             <div class="field">
                                    <label>GDPR</label>
                                    <div class="ui checkbox">
                                        <input data-validation="checkbox_group" data-validation-qty="min1" data-validation-error-msg="Please accept that the provided data will be processed and used by European Work Power" type="checkbox" name="gdpr" value="1" required="">
                                        <label>I agree that the personal data provided by me will be used to receive data and information from European Work Power</label>
                                    </div>
                                </div>

                                <button class="ui button aplica" type="submit">Apply</button>

                                 

                            </div>


                        </div>

                    </form>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.4/semantic.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/utils.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/intlTelInput-jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/intlTelInput.min.js"></script>



<script type="text/javascript">
      $('#example2').calendar({
          type: 'date'
        });
    $('.ui.dropdown').dropdown();
        
  var input = document.querySelector("#phone");
window.intlTelInput(input, {
hiddenInput: "phone",
separateDialCode: true,
  initialCountry: "auto",
  geoIpLookup: function(callback) {
    $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
      var countryCode = (resp && resp.country) ? resp.country : "";
      callback(countryCode);
    });
  },
  utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/utils.min.js" // just for formatting/placeholders etc
});
   
    </script>



</body>
</html>