<?php
global $app_url,$con;
mysqli_set_charset( $con, 'utf8'); 
?>
<div id="header-bottom-wrap" class="is-clearfix">
  <div id="header-bottom" class="site-header-bottom">
    <div id="header-bottom-inner" class="site-header-bottom-inner ">
      <section class="hero slider is-clearfix ">
        <h2 class="display-none">slider</h2>
        <div class="rev_slider_wrapper fullscreen-container ">
          <div id="rev_slider_1" class="rev_slider tp-overflow-hidden fullscreenbanner" data-version="5.4.7" style="display:none">
            <a href="#welcome" class="slider-scroll-down">Scroleaza in jos</a>
            <ul>  
              <li data-transition="fade" data-thumb="./assets/images/icons/1.png" data-title="Angajator german" data-param1="" data-param2="./assets/images/icons/1.png">
                <img alt="Joo - Niche Multi-Purpose HTML Template" class="rev-slidebg" src="./assets/images/img-2.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-kenburns="off" data-duration="30000" data-ease="Linear.easeNone"
                  data-scalestart="100" data-scaleend="115" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="15">

                <div class="tp-caption tp-resizeme large_text" data-x="left" data-hoffset="['-105','-105','0','0']" data-y="center" data-voffset="['-56','-56','-56','-56']" data-width="none" data-height="none" data-whitespace="nowrap"
                  data-type="text" data-responsive-offset="on" data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1600,"to":"o:1;","delay":1200,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"opacity:0;","ease":"nothing"}]'
                  data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"> Atunci cand
                    STABILITATEA, SERIOZITATEA, CALITATEA <br>
 Primeaza (conteaza/sunt primele) pentru tine si ai tai.
</div>
                <a class="tp-caption tp-resizeme button is-primary" href="#apply" data-frames='[{"delay":1600,"speed":2000,"frame":"0","from":"y:[120%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                  data-x="left" data-hoffset="['-102','-102','0','0']" data-y="center" data-voffset="['82','82','0','0']" data-type="button">
                  <span>Aplica acum</span>
                  <span class="icon is-small">
                    <i class="ion-ios-arrow-round-forward"></i>
                  </span>
                </a>
              </li>
              <!-- slide -->
              <li data-transition="fade" data-thumb="./assets/images/icons/2.png" data-title="Suport" data-param1="Lorem ipsum dolor sit ultrices eleifend gravi." data-param2="./assets/images/icons/2.png">
                <img alt="Joo - Niche Multi-Purpose HTML Template" class="rev-slidebg" src="./assets/images/img-3.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-kenburns="off" data-duration="30000" data-ease="Linear.easeNone"
                  data-scalestart="100" data-scaleend="115" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="15">

                <div class="tp-caption tp-resizeme large_text" data-x="left" data-hoffset="['-105','-105','0','0']" data-y="center" data-voffset="['-56','-56','-56','-56']" data-width="none" data-height="none" data-whitespace="nowrap"
                  data-type="text" data-responsive-offset="on" data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1600,"to":"o:1;","delay":1200,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"opacity:0;","ease":"nothing"}]'
                  data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"> DIURNA ZILNICA, ASIGURARE DE SANATATE, SPORURI DE PERFORMANTA,CONCEDII PLATITE,<br> CONTRACT PE PERIOADA NEDETERMINATA
</div>
                <a class="tp-caption tp-resizeme button is-primary" href="#apply" data-frames='[{"delay":1600,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                  data-x="left" data-hoffset="['-102','-102','0','0']" data-y="center" data-voffset="['82','82','0','0']" data-type="button">
                  <span>Aplica acum</span>
                  <span class="icon is-small">
                    <i class="ion-ios-arrow-round-forward"></i>
                  </span>
                </a>
              </li>
              <!-- slide -->
              <li data-transition="fade" data-thumb="./assets/images/icons/3.png" data-title="Seriozitate și Încredere" data-param1="Lorem ipsum dolor sit ultrices eleifend gravi." data-param2="./assets/images/icons/3.png">
                <img alt="Joo - Niche Multi-Purpose HTML Template" class="rev-slidebg" src="./assets/images/slider_bg04.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-kenburns="off" data-duration="30000" data-ease="Linear.easeNone"
                  data-scalestart="100" data-scaleend="115" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="15">
                <div class="tp-caption tp-resizeme large_text" data-x="left" data-hoffset="['-105','-105','0','0']" data-y="center" data-voffset="['-56','-56','-56','-56']" data-width="none" data-height="none" data-whitespace="nowrap"
                  data-type="text" data-responsive-offset="on" data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1600,"to":"o:1;","delay":1200,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"opacity:0;","ease":"nothing"}]'
                  data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"> Ne ocupam de tot pentru tine:
       INTERVIU SI SUPORT TELEFONIC, <br>TRANSPORT ASIGURAT PANA LA ANGAJATOR, SUPORT PENTRU RELOCARE
</div>
                <a class="tp-caption tp-resizeme button is-primary" href="#apply" data-frames='[{"delay":1600,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                  data-x="left" data-hoffset="['-102','-102','0','0']" data-y="center" data-voffset="['82','82','0','0']" data-type="button">
                  <span>Aplica acum</span>
                  <span class="icon is-small">
                    <i class="ion-ios-arrow-round-forward"></i>
                  </span>
                </a>
              </li>
              <!-- slide -->
              <li data-transition="fade" data-thumb="./assets/images/icons/4.png" data-title="Costuri" data-param1="Lorem ipsum dolor sit ultrices eleifend gravi." data-param2="./assets/images/icons/4.png">
                <img alt="Joo - Niche Multi-Purpose HTML Template" class="rev-slidebg" src="./assets/images/slider/1.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-kenburns="off" data-duration="30000" data-ease="Linear.easeNone"
                  data-scalestart="100" data-scaleend="115" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="15">

                <div class="tp-caption tp-resizeme large_text" data-x="left" data-hoffset="['-105','-105','0','0']" data-y="center" data-voffset="['-56','-56','-56','-56']" data-width="none" data-height="none" data-whitespace="nowrap"
                  data-type="text" data-responsive-offset="on" data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1600,"to":"o:1;","delay":1200,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"opacity:0;","ease":"nothing"}]'
                  data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"> ZERO
           Costuri & Riscuri </div>
                <a class="tp-caption tp-resizeme button is-primary" href="#apply" data-frames='[{"delay":1600,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                  data-x="left" data-hoffset="['-102','-102','0','0']" data-y="center" data-voffset="['82','82','0','0']" data-type="button">
                  <span>Aplica acum</span>
                  <span class="icon is-small">
                    <i class="ion-ios-arrow-round-forward"></i>
                  </span>
                </a>
              </li>
              <!-- slide -->
            </ul>
          </div>
          <!-- .rev_slider -->
        </div>
        <!-- .rev_slider_wrapper -->
      </section>
      <!-- .slider -->
    </div>
    <!-- #header-bottom-inner -->
  </div>
  <!-- #header-bottom -->
</div>
<!-- #header-bottom-wrap -->
<!-- import content layouts and modules -->
<div id="content-main-wrap" class="is-clearfix">
  <div id="content-area" class="site-content-area">
    <div id="content-area-inner" class="site-content-area-inner">
      <!-- import content layouts and modules -->
      <!-- start adding page content -->

      <section id="services" class="section services-section has-background-primary-light is-clearfix">
        <div class="container">
          <div class="columns is-variable is-multiline is-4">
            <div class="column is-5-desktop is-12-tablet">
              <p class="heading-title-top">cateva din beneficiile de a lucra prin noi</p>
              <h1 class="heading-title style-3 has-text-left">Beneficii</h1>
            </div>
          </div>
          <br>
          <div class="columns is-variable is-6 is-multiline boxes-style-2">
            <div class="column is-6" data-aos="fade">
              <div style="min-height: 400px;" class="box-item">
                <a href="./pages/services.html">
                  <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/icons/4.png"> </a>
                <h3>
                  <a href="./pages/services.html">Angajator german</a>
                </h3>
                <p>Colaborăm cu peste 300 de angajatori germani care își respectă contractele și angajații. Ne vom asigura că oamenii pentru care vei lucra sunt de încredere și îți oferă acea stabilitate pentru care germanii sunt faimoși.</p>
              </div>
              <!-- .box-item -->
            </div>
            <div class="column is-6" data-aos="fade">
              <div style="min-height: 400px;" class="box-item">
                <a href="./pages/services.html">
                  <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/icons/3.png"> </a>
                <h3>
                  <a href="./pages/services.html">Suport</a>
                </h3>
                <p>Punem la dispoziția ta un asistent personal care: îți va face o ofertă de muncă cât mai avantajoasă, ținând cont de pregătirea, experiența și nevoile tale. Te va sprijini pe durata interviului cu angajatorul german. Îți va oferi suport pe întreaga durată a călătoriei până la angajator.</p>
              </div>
              <!-- .box-item -->
            </div>
            <div class="column is-6" data-aos="fade">
              <div style="min-height: 400px;" class="box-item">
                <a href="./pages/services.html">
                  <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/icons/1.png"> </a>
                <h3>
                  <a href="./pages/services.html">Seriozitate și încredere</a>
                </h3>
                <p>Contractele se semnează pe Germania direct cu angajatorul tău. Totul este legal, în conformitate cu cerințele promulgate de U.E.</p>
              </div>
              <!-- .box-item -->
            </div>
            <div class="column is-6" data-aos="fade">
              <div style="min-height: 400px;" class="box-item">
                <a href="./pages/services.html">
                  <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/icons/3.png"> </a>
                <h3>
                  <a href="./pages/services.html">Costuri</a>
                </h3>
                <p>Ne vom ocupa de tot procesul de recrutare fără niciun cost din partea ta! Odată ce vei fi acceptat la jobul pentru care ai aplicat, poți să începi să îți faci bagajele. Costurile transportului vor fi suportate integral de noi.</p>
              </div>
              <!-- .box-item -->
            </div>
          </div>
        </div>
      </section>

      <section id="apply" class="section quote-section padding-bottom-none is-clearfix">
        <div class="container">
          <div class="columns is-variable is-2 is-multiline">
            <div class="column is-8-desktop is-12-tablet">
              <h2 class="heading-title style-3 has-text-left"> APLICĂ AICI PENTRU O 
                <span class="has-text-primary">OFERTĂ PERSONALIZATĂ</span>
              </h2>
              <!--<p class="heading-title-bottom">Lorem ipsum dolor sit amet, consectetur adipiscing elit Nulla chronocrator accumsan, metus ultrices eleifend gravi.</p> -->
              <!-- successful form message -->
              <div class="overhang-message-content is-hidden success">
                <span class="icon">
                  <i class="ion-md-notifications"></i>
                </span> Thank You! Your message was sent successfully. </div>
              <!-- error form message -->
              <div class="overhang-message-content is-hidden error">
                <span class="icon">
                  <i class="ion-md-notifications"></i>
                </span> Oops! Something went wrong, we couldn't send your message. </div>

              <iframe onLoad="submits(this.contentWindow.location);" name="formi" style="height:850px;width:100%" src="<?= $app_url;?>/form"></iframe>

            </div>
            <div class="column is-4-desktop is-12-tablet">
              <br>
              <br>
              <br>
              <br>
              <img alt="EU-TRUCKERS" src="<?= $app_url;?>/assets/images/truck.png"> </div>
          </div>
        </div>
      </section>

      <?php

                           $sql = "SELECT * FROM job_offers WHERE active='1' AND language_short='ro'";
                           $result = $con->query($sql);

                           if ($result->num_rows > 0) {
                               
                            echo '<section id="news" class="section news-section is-clearfix">
                            <div class="container">
                              <h1 class="heading-title style-3">Uite câteva dintre joburile disponibile în acest moment</h1>
                              <p class="heading-title-top has-text-centered">Dacă nu găsești ceva potrivit, <a href="#apply">Aplică Aici</a>, iar noi vom căuta o ofertă cât mai avantajoasă pentru tine și te vom suna imediat!</p>
                    
                              <div class="blog-list style-3 columns is-variable is-4 is-multiline">';

                               while($row = $result->fetch_assoc()) {

                  echo '<a class="column is-12" href="'.$app_url.'/job/'. $row["job_offers_id"].'">

                  <article class="blog-post" style="padding: 14px 10px;border-radius: 10px;background-color: #f8f8f8;border: solid 2px #f1f1f1;">
                  <h2 class="entry-title" style="margin-bottom: 5px !important;">'. $row["title"].'</h2>
                  <div class="post-meta" style="margin-bottom: 0px;">
                                                   <ul>
                                                     <li>
                                                       <span style="color: rgba(75,80,93,.8);font-weight: 500;font-size: 90%;">'. $row["city_location"].'</span>
                                                     </li>
                                                   </ul>
                                                 </div>

                                             </article>
                                           </a>';


                               }

                           echo '</div>
                           </div>
                         </section>';    
                           } else {
                               //echo "0 results";
                           }

        ?>

      
      <section id="testimonials" class="section testimonials-section has-background-primary-light is-clearfix">
        <div class="container">
          <p class="heading-title-top has-text-centered">recenzii</p>
          <h1 class="heading-title style-3">o parte din recenziile noastre</h1>
          <div class="testimonials  owl-carousel dots carousel-items-3 columns-style-1 ">
            <div class="testimonials-item">
              <p>O companie care intr-adevar intelege nevoile soferilor din toate punctele de vedere, asa ca nu ezitati sa aplicati.<br>
Recomand cu mare incredere!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100005792053981/picture?type=large">
              <h3>Adrian Titus
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>O companie care se gandeste la nevoile soferilor!</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100000878227676/picture?type=large">
              <h3>Dan Floruta
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Recomand cu toată încrederea! Firmă serioasă care ține cont de nevoile clienților.</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100002437091632/picture?type=large">
              <h3>Enache Alexandru
                <br>
                <span>Facebook</span>
              </h3>
            </div>
            <div class="testimonials-item">
              <p>Recomand cu incredere eu sînt foarte multumit din toate punctele de vedere</p>
              <img alt="Joo - Niche Multi-Purpose HTML Template" src="https://graph.facebook.com/100025031414151/picture?type=large">
              <h3>Dumitru Coroiu
                <br>
                <span>Facebook</span>
              </h3>
            </div>
          </div>
        </div>
      </section>
    </div>
    <!-- #content-area-inner -->
  </div>
  <!-- #content-area -->
</div>
