<?php
global $app_url, $con;
mysqli_set_charset( $con, 'utf8'); 
?>
<div id="header-bottom-wrap" class="is-clearfix">
        <div id="header-bottom" class="site-header-bottom">
          <div id="header-bottom-inner" class="site-header-bottom-inner ">
            <section style="background: #f8f8f8 url(<?php echo $app_url;?>/assets/images/slider_bg04.jpg) no-repeat top center;" class="hero page-title is-medium has-text-centered about">
              <div class="hero-body">
                <div class="container">
                  <h1>Iti multumim ca ai aplicat!</h1>
                  <h3>EU-TRUCKERS - EWP BRAND</h3>
                </div>
                <!-- .hero-body -->
              </div>
              <!-- .container -->
            </section>
            <!-- .page-title -->
          </div>
          <!-- #header-bottom-inner -->
        </div>
        <!-- #header-bottom -->
      </div>

      <div id="content-main-wrap" class="is-clearfix">
              <div id="content-area" class="site-content-area">
                <div id="content-area-inner" class="site-content-area-inner">


                    <?php

$sql = "SELECT * FROM job_offers WHERE active='1' AND language_short='ro'";
$result = $con->query($sql);

if ($result->num_rows > 0) {
    
 echo '<section id="news" class="section news-section is-clearfix">
 <div class="container">
   <h1 class="heading-title style-3">Uite câteva dintre joburile disponibile în acest moment</h1>
   <p class="heading-title-top has-text-centered">Dacă nu găsești ceva potrivit, <a href="#apply">Aplică Aici</a>, iar noi vom căuta o ofertă cât mai avantajoasă pentru tine și te vom suna imediat!</p>

   <div class="blog-list style-3 columns is-variable is-4 is-multiline">';

    while($row = $result->fetch_assoc()) {

echo '<a class="column is-12" href="'.$app_url.'/job/'. $row["job_offers_id"].'">

<article class="blog-post" style="padding: 14px 10px;border-radius: 10px;background-color: #f8f8f8;border: solid 2px #f1f1f1;">
<h2 class="entry-title" style="margin-bottom: 5px !important;">'. $row["title"].'</h2>
<div class="post-meta" style="margin-bottom: 0px;">
                        <ul>
                          <li>
                            <span style="color: rgba(75,80,93,.8);font-weight: 500;font-size: 90%;">'. $row["city_location"].'</span>
                          </li>
                        </ul>
                      </div>

                  </article>
                </a>';


    }

echo '</div>
</div>
</section>';    
} else { ?>

<section class="section introduction is-clearfix">
                    <div class="container">
                      <p class="heading-title-top has-text-centered">EU-TRUCKERS UN BRAND EWP</p>
                      <h1 class="heading-title style-3">Joburi disponibile</h1>
                      <p class="has-text-centered">Ne pare rau dar momentan nu sunt joburi disponibile in limba romana! Te rugam sa verifici pagina de joburi in limba engleza sau sa revii mai tarziu. Iti multumim!</p>
                      <br>
                      <br>
                      <br>
                    </div>
                    </section>

<?php    
}

?>

                </div>
                <!-- #content-area-inner -->
              </div>
              <!-- #content-area -->
            </div>
