<?php
global $app_url;
?>
<div style="display:none" id="footer-top-wrap" class="is-clearfix">
  <div id="footer-top" class="site-footer-top">
    <div id="footer-top-inner" class="site-footer-top-inner ">
      <section class="hero clients-section is-clearfix">
        <div class="container">
          <div class="columns is-variable is-4 is-multiline">
            <div class="column is-2-desktop is-12-tablet">
              <h1 class="heading-title style-3 has-text-left">our partners</h1>
            </div>
            <div class="column is-10-desktop is-12-tablet">
              <nav class="clients-list level  owl-carousel no-dots carousel-items-5">
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/7.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/8.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/9.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/7.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/8.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/9.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/7.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/8.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/9.png"> </a>
                </div>
                <div class="client-item has-text-centered level-item">
                  <a href="#" target="_blank">
                    <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/clients/7.png"> </a>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </section>
    </div>
    <!-- #footer-top-inner -->
  </div>
  <!-- #footer-top -->
</div>
<!-- #footer-top-wrap -->
<div style="display:none" id="footer-wrap" class="is-clearfix">
  <footer id="footer" class="site-footer">
    <div id="footer-inner" class="site-footer-inner container">
      <div class="columns is-variable is-6 is-multiline">
        <div class="column is-4">
          <div class="widget widget-html">
            <div class="textwidget">
              <div id="footer-logo" class="site-logo ">
                <a href="./index.html">
                  <img alt="Joo - Niche Multi-Purpose HTML Template" src="./assets/images/logo/logo2.png">
                  <span class="logo-text">Logistics</span>
                </a>
              </div>
              <!-- #footer-logo -->
              <br>
              <p>The main component of a healthy environment for self esteem is that it needs be nurturing. It should provide unconditional warmth.</p>
              <div class="footer-social-links ">
                <ul>
                  <li>
                    <a href="#" target="_blank">
                      <span class="icon">
                        <i class="fab fa-facebook-f"></i>
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#" target="_blank">
                      <span class="icon">
                        <i class="fab fa-twitter"></i>
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#" target="_blank">
                      <span class="icon">
                        <i class="fab fa-linkedin-in"></i>
                      </span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- .textwidget -->
          </div>
        </div>
        <!-- .column -->
        <div class="column">
          <div class="widget widget-links">
            <h3 class="widget-title ">services</h3>
            <ul>
              <li>
                <a href="./index.html">Air freight</a>
              </li>
              <li>
                <a href="./index.html">sea freight</a>
              </li>
              <li>
                <a href="./index.html">land transport</a>
              </li>
              <li>
                <a href="./index.html">groupage</a>
              </li>
              <li>
                <a href="./index.html">consultancy</a>
              </li>
            </ul>
          </div>
          <!-- .widget -->
        </div>
        <!-- .column -->
        <div class="column">
          <div class="widget widget-links">
            <h3 class="widget-title ">information</h3>
            <ul>
              <li>
                <a href="./index.html">Warehousing</a>
              </li>
              <li>
                <a href="./index.html">Ocean Freight</a>
              </li>
              <li>
                <a href="./index.html">Air freight</a>
              </li>
              <li>
                <a href="./index.html">land transport</a>
              </li>
              <li>
                <a href="./index.html">groupage</a>
              </li>
            </ul>
          </div>
          <!-- .widget -->
        </div>
        <!-- .column -->
        <div class="column is-4">
          <div class="widget widget-form">
            <h3 class="widget-title ">newsletter</h3>
            <p>The main component of a healthy environment for self esteem that industry.</p>
            <br>
            <form>
              <div class="field">
                <div class="control is-expanded">
                  <input class="input" type="text" placeholder="your@email.com">
                  <button type="submit" class="button is-radiusless">
                    <span class="icon">
                      <i class="ion-ios-arrow-round-forward-outline"></i>
                    </span>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- .column -->
      </div>
      <!-- .columns -->
    </div>
    <!-- #footer-inner -->
  </footer>
  <!-- #footer -->
</div>

<!-- #footer-wrap -->
<div id="footer-bottom-wrap" class="is-clearfix">
  <div id="footer-bottom" class="site-footer-bottom">
    <div id="footer-bottom-inner" class="site-footer-bottom-inner ">
      <section class="section footer-bottom-content">
        <div class="container">
          <h2 class="display-none">footer</h2>
          <div class="level">
            <div class="level-left">
              <span class="footer-copyright">
                <a href='/'>EU-TRUCKERS</a> ©
                <span class='current-year'></span> Component of <a href='https://europeanworkpower.com/'>European Work Power</a> </span>
            </div>
            <!-- .level-left -->
            <div class="level-right">
              <span class="footer-copyright">
                 Developed and maintend by <a href='https://jivate.com/'>JIVATE GROUP</a> </span>
            </div>
            <!-- .level-right -->
          </div>
          <!-- .level -->
        </div>
      </section>
      <!-- .footer-bottom-content -->
    </div>
    <!-- #footer-bottom-inner -->
  </div>
  <!-- #footer-bottom -->
</div>
<!-- #footer-bottom-wrap -->

</div>
<!-- #site-wrap -->
<script src="<?= $app_url;?>/assets/js/vendor.min.js?v=1557446391092"></script>
<script src="<?= $app_url;?>/assets/js/scripts.min.js?v=1557446391092"></script>
<script src="<?= $app_url;?>/assets/js/custom.js?v=1557446391092"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.4/components/form.min.js"></script>



<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '3838921602887191');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=3838921602887191&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125993171-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125993171-1');
</script>

<script>
function submits(content){
  console.log(content);
  if(content.href=="https://eu-truckers.com/en/thank-you"){
    fbq('track', 'Lead', {
        language: 'EN'
    });
    console.log("Facut bine");
  }else{
    console.log("Nefacut");
  }

}</script>

</body>
</html>
