<?php
global $app_url;
?>
<!DOCTYPE html>
<html lang="en" class="no-js no-svg">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Jozoor">
    <meta name="description" content="Joo - Niche Multi-Purpose HTML Template">
    <meta name="keywords" content="creative, niche, responsive, html5, css3, multipurpose, all in one, html, template">
    <title>EU-TRUCKERS - Joburi in toata Europa</title>
    <link rel="stylesheet" href="<?=$app_url;?>/assets/css/vendor.min.css">
    <link rel="stylesheet" href="<?=$app_url;?>/assets/css/styles.min.css">
    <link rel="stylesheet" href="<?=$app_url;?>/assets/css/custom.css">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600&v=1557446305971" rel="stylesheet">
    <!-- cdn icon fonts
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css?v=1557446305971" crossorigin="anonymous">
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css?v=1557446305971">
			<link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css?v=1557446305971" rel="stylesheet">
		-->
    <link rel="apple-touch-icon" sizes="57x57" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?=$app_url;?>/assets/images/favicons/apple-touch-icon-180x180.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="Joo Template">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=$app_url;?>/assets/images/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=$app_url;?>/assets/images/favicons/favicon-16x16.png">
    <link rel="shortcut icon" href="<?=$app_url;?>/assets/images/favicons/favicon.ico">
    
   

    <link href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.4/components/form.min.css" rel="stylesheet" type="text/css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/grid.min.css" rel="stylesheet" type="text/css">
    <link href=" https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/input.min.css" rel="stylesheet" type="text/css">

    
   
    
    <style>
    .nav-menu-dropdown.style-2>li>ul {
    min-width: 115px;
    }
    body.header-center-overlay header, body.header-transparent header, body.header-transparent-overlay header {
    top: 50px;
    position: absolute;
    z-index: 20;
    }
    .tp-caption.large_text {
      font-size: 2.2rem !important;
    }
    body.header-transparent-overlay:not(.responsive-layout):not(.header-hamburger-menu) header#header:not(.hide-on-scroll):not(.show-on-scroll) .level:not(.top), body.header-transparent:not(.responsive-layout):not(.header-hamburger-menu) header#header:not(.hide-on-scroll):not(.show-on-scroll) .level:not(.top) {
    border-bottom: 0px solid #4b505d;
    }
    
    .hamburger-menu .hamburger-menu-icon, .hamburger-menu .hamburger-menu-icon:after, .hamburger-menu .hamburger-menu-icon:before {
    background-color: #ffffff !important;
    }

    @media only screen and (max-width: 900px) {
      .site-logo{
        display: none !important;
      }
      .tp-caption.tp-resizeme.large_text{
      font-size: 2rem !important;
      }

      .share_button > :not(i){
        display: none;
      }

      iframe{
        height: 900px !important;
      }

      .rev_slider .slider-scroll-down:after {
      width: 0px !important;
      }
    }

    @media only screen and (min-width: 900px) {
      .show-mobile{
        display: none !important;
      }
    }

    .tp-tab-content > .icon{
      display: none !important;
    }


    .hesperiden .tp-tab.selected .tp-tab-content .icon {
      display: none !important;
    }

    </style>
  </head>
  <body class="active-pageloader corporate logistics hide-on-scroll header-menu-with-icons header-transparent header-menu-border-bottom header-topbar topbar-background dark-color footer-widgets footer-background dark-color submenu-show-arrow-right menu-is-capitalized submenu-is-capitalized logo-text-is-capitalized page-index">
    <div class="pageloader is-active"></div>
    <div id="site-wrap" class="site">
      <div id="header-top-wrap" class="is-clearfix">
        <div id="header-top" class="site-header-top">
          <div id="header-top-inner" class="site-header-top-inner container">
            <div class="level">
              <div class="level-left">
                <ul class="topbar-info ">
                  <li>
                    <a href="#">
                      <span class="icon">
                        <i class="icon-clock"></i>
                      </span> Monday - Friday : 09:00 - 17:00 </a>
                  </li>
                  <li>
                    <a href="mailto:contact@eu-truckers.com">
                      <span class="icon">
                        <i class="icon-envelope"></i>
                      </span> contact@eu-truckers.com </a>
                  </li>
                  <li>
                    <a href="tel:+40735183011">
                      <span class="icon">
                        <i class="icon-phone"></i>
                      </span> +40 735 183 011 </a>
                  </li>
                </ul>
              </div> 
              <!-- .level-left -->
              <div class="level-right">
                <ul class="header-menu-icons social">
                  <li>
                    <a href="https://facebook.com/EuTruckers/" target="_blank">
                      <span class="icon">
                        <i class="fab fa-facebook-f"></i>
                      </span>
                    </a>
                  </li>
                </ul>
                <ul class="nav-menu-dropdown style-2 global-style on-click">
                  <li>
                    <a href="#">
                      <span class="flag-icon flag-icon-ro"></span>English</a>
                    <ul>
                      <li>
                        <a href="<?= $app_url;?>/">
                          <span class="flag-icon flag-icon-ro"></span>Română</a>
                      </li>
                      <li>
                        <a href="<?= $app_url;?>/de/">
                          <span class="flag-icon flag-icon-de"></span>Deutsche</a>
                      </li>
                    </ul>
                  </li>
                </ul>
                <!-- .header-menu-icons -->
              </div>
              <!-- .level-right -->
            </div>
            <!-- .level -->
          </div>
          <!-- #header-top-inner -->
        </div>
        <!-- #header-top -->
      </div>
      <!-- #header-top-wrap -->
      <div id="header-wrap" class="is-clearfix">
        <header id="header" class="site-header">
          <div id="header-inner" class="site-header-inner container">
            <div class="level">
              <div class="level-left">
                <div id="header-logo" class="site-logo ">
                  <div id="logo-inner" class="site-logo-inner">
                    <a href="<?= $app_url;?>/en/">
                      <img style="max-height: 86px;" alt="Joo - Niche Multi-Purpose HTML Template" src="<?= $app_url;?>/assets/images/logo-eu.png">
                    </a>
                  </div>
                  <!-- #logo-inner -->
                </div>
                <!-- #header-logo -->
              </div>
              <!-- .level-left -->
              <div class="level-right">
                <div class="nav-wrap">
                  <nav class="main-navigation right">
                    <ul class="menu">
                      <li class="mega-menu niche-templates">
                        <a href="<?= $app_url;?>/en/">Home</a>
                      </li>
                      <li class="mega-menu niche-templates">
                        <a href="<?= $app_url;?>/en/about/">About us</a>
                      </li>
                      <li class="mega-menu niche-templates">
                        <a href="<?= $app_url;?>/en/jobs/">Available jobs</a>
                      </li>
                      <li class="mega-menu niche-templates">
                        <a href="<?= $app_url;?>/en/contact/">Contact</a>
                      </li>
                    </ul>
                  </nav>
                  <!-- #site-navigation -->
                </div>
                <!-- #nav-wrap -->
                <!-- .header-menu-icons -->
                <a href="<?= $app_url?>/en/#apply" class="button is-white">Apply now</a>

                <div class="nav-wrap show-mobile">
                  <nav class="main-navigation right">
                    <ul class="menu">
                      <li class="mega-menu niche-templates">
                        <a href="<?= $app_url;?>/"><span class="flag-icon flag-icon-ro"></span> Română</a>
                      </li>
                      <li class="mega-menu niche-templates">
                        <a href="<?= $app_url;?>/de/"><span class="flag-icon flag-icon-de"></span> Deutsche</a>
                      </li>

                    </ul>
                  </nav>
                  <!-- #site-navigation -->
                </div>

                <div class="modal search-form-overlay">
                  <div class="modal-background"></div>
                  <div class="modal-content">
                    <form class="widget-form">
                      <div class="field">
                        <div class="control is-expanded">
                          <input class="input" type="text" placeholder="Search...">
                          <button type="submit" class="button">
                            <span class="icon">
                              <i class="icon-magnifier"></i>
                            </span>
                          </button>
                        </div>
                      </div>
                    </form>
                  </div>
                  <button class="modal-close is-large" aria-label="close"></button>
                </div>
                <!-- .modal.search-form-overlay -->
              </div>
              <!-- .level-right -->
            </div>
            <!-- .level -->
          </div>
          <!-- #header-inner -->
        </header>
        <!-- #header -->
      </div>
      <!-- #header-wrap -->
