<?php
session_start();
if(!isset($_SESSION['org_referer']))
{
    $_SESSION['org_referer'] = $_SERVER['HTTPS_REFERER'];
}
$con = mysqli_connect("remotemysql.com","GkgXTGrlGQ","JlMYNFbrJC","GkgXTGrlGQ");

// Check connection
if (mysqli_connect_errno())
  {
  echo "Failed to connect to MySQL: " . mysqli_connect_error();
  }

include "includes/parts/header.php";?>

<div class="breadcumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcumb-wrap text-center">
                    <h2>Termeni si conditii</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <p>Preambul<br />Prezenta Politică de Confidențialitate și Protecție a Datelor cu Caracter Personal a fost creată av&acirc;nd &icirc;n vedere intrarea &icirc;n vigoare &icirc;ncep&acirc;nd cu data de 25 mai 2018 a Regulamentului (UE) 2016/679 al Parlamentului European și al Consiliului Europei din 27 aprilie 2016 privind protecția datelor cu caracter personal.</p>
                <p>Această politică prezintă principiile și măsurile luate pentru asigurarea conformităț&icirc;i prelucrării datelor conform Regulamentului UE 2016/679. Ne propunem să avem cu vizitatorii site-ului nostru o relație bazată pe bună-credința, etică, &icirc;ncredere și transparență.</p>
                <p>Navigarea pe site-ul eu-truckers.com echivalează cu citirea, &icirc;nțelegerea și acceptarea acestei Politici de utilizare a site-ului.</p>
                <p>Principii<br />Prezenta Politică de Confidențialitate și Protejare a Datelor cu Caracter Personal este construită respect&acirc;nd următoarele principii:</p>
                <p>Datele colectate sunt relevante pentru scopul activității care au generat colectarea lor iar aceste scopuri sunt determinate, explicite și legitime (&icirc;ndeplinirea obligațiilor contractuale și comerciale ale societății față de clienții săi).<br />Toate datele sunt colectate sunt securizate prin luarea de măsuri tehnice corespunzătoare. &Icirc;n plus, site-ul este securizat prin protocolul HTTPS.<br />Toate datele sunt prelucrate &icirc;n mod legal, echitabil și transparent fată de persoana vizată, &icirc;n conformitate cu dispozițiile legale &icirc;n vigoare.<br />Toate datele colectate sunt păstrate pe o perioadă care nu depășește perioada necesară &icirc;ndeplinirii scopurilor &icirc;n care sunt prelucrate datele.<br />Drepturile persoanelor vizate<br />Potrivit dispozițiilor Regulamentului nr. 679/2016 (Regulamentul general privind protecția datelor) persoană vizată are următoarele drepturi:</p>
                <p>dreptul de acces;<br />dreptul la rectificare;<br />dreptul la ștergerea datelor;<br />dreptul la restricționarea prelucrării;<br />dreptul la portabilitatea datelor;<br />dreptul la opoziție;<br />dreptul de a se opune proceselor decizionale automate (cookies).<br />Definiții termeni importanți (cf. legislației)<br />Ce sunt datele personale<br />Datele personale se definesc ca fiind acele informații privind o persoană fizică identificată sau identificabilă (&bdquo;persoană vizată&rdquo;), referitoare la Nume, Adresa, Cod Numeric Personal, IP, Număr de telefon, date de localizare, un identificator online, sau la unul sau mai multe elemente specifice, proprii identității sale fizice, fiziologice, genetice, psihice, economice, culturale sau sociale.</p>
                <p>Ce &icirc;nseamnă Prelucrare<br />Prelucrare &icirc;nseamnă orice operațiune sau set de operațiuni efectuate asupra datelor cu caracter personal sau asupra seturilor de date cu caracter personal, cu sau fără utilizarea de mijloace automatizate, cum ar fi colectarea, &icirc;nregistrarea, organizarea, structurarea, stocarea, adaptarea sau modificarea, extragerea, consultarea, utilizarea, divulgarea prin transmitere, diseminarea sau punerea la dispoziție &icirc;n orice alt mod, alinierea sau combinarea, restricționarea, ștergerea sau distrugerea;</p>
                <p>Ce &icirc;nseamnă Operator<br />Operator &icirc;nseamnă persoana fizică sau juridică, autoritatea publică, agenția sau alt organism care, singur sau &icirc;mpreună cu altele, stabilește scopurile și mijloacele de prelucrare a datelor cu caracter personal; atunci c&acirc;nd scopurile și mijloacele prelucrării sunt stabilite prin dreptul Uniunii sau dreptul intern, operatorul sau criteriile specifice pentru desemnarea acestuia pot fi prevăzute &icirc;n dreptul Uniunii sau &icirc;n dreptul intern;</p>
                <p>Ce &icirc;nseamnă Destinatar<br />Destinatar &icirc;nseamnă persoană fizică sau juridică, autoritatea publică, agenție sau alt organism căreia (căruia) &icirc;i sunt divulgate datele cu caracter personal, indiferent dacă este sau nu o parte terță. Cu toate acestea, autoritățile publice cărora li se pot comunica date cu caracter personal &icirc;n cadrul unei anumite anchete &icirc;n conformitate cu dreptul Uniunii sau cu dreptul intern nu sunt considerate destinatari; prelucrarea acestor date de către autoritățile publice respective respectă normele aplicabile &icirc;n materie de protecție a datelor, &icirc;n conformitate cu scopurile prelucrării;</p>
                <p>Ce &icirc;nseamnă Parte Terță<br />Parte terță &icirc;nseamnă o persoană fizică sau juridică, autoritate publică, agenție sau organism altul dec&acirc;t persoană vizată, operatorul, persoană &icirc;mputernicită de operator și persoanele care, sub directă autoritate a operatorului sau a persoanei &icirc;mputernicite de operator, sunt autorizate să prelucreze date cu caracter personal</p>
                <p>Ce &icirc;nseamnă Consimțăm&acirc;nt<br />Consimțăm&acirc;nt al persoanei vizate &icirc;nseamnă orice manifestare de voință liberă, specifică, informată și lipsită de ambiguitate a persoanei vizate prin care această acceptă, printr-o declarație sau printr-o acțiune fără echivoc, că datele cu caracter personal care o privesc să fie prelucrate.</p>
                <p>Cine suntem<br />Site-ul eu-truckers.com este deținut de către EUROPEAN WORK POWER SRL av&acirc;nd datele de identificare Reg. Com. J32/283/2018 și CUI RO 38941000 și datele de contact Tel.: +40735183011 și candidati@eu-truckers.com</p>
                <p>Ce date personale colectăm și de ce le colectăm<br />Colectăm pe bază de consimțăm&acirc;nt doar acele date cu caracter personal necesare pentru a putea realiza cu succes cerințele utilizatorilor noștri. &Icirc;n funcție de interacțiunile pe care utilizatorii le au cu site-ul nostru și de la caz la caz &icirc;n relație cu necesitatea implicată, datele cu caracter personal pe care le colectăm pot fi următoarele:</p>
                <p>Date de identificare și contact</p>
                <p>Nume și prenume &ndash; pentru &icirc;nscrierea la cursurile noastre sau pentru &icirc;ncheierea unui contract de prestări servicii.<br />Adresa de email &ndash; pentru comunicare electronică, pentru transmiterea și primirea de documente necesare desfășurării colaborării.<br />Număr de telefon &ndash; pentru comunicare flexibilă și promptă<br />Alte date de identificare din cartea de identitate (adresa, serie/număr buletin, cod numeric personal, detalii de plată) necesare &icirc;ntocmirii facturilor fiscale de servicii.<br />Date profesionale</p>
                <p>Loc de muncă, poziție, vechime, experiența profesională (necesare doar &icirc;n cazul participării la cursuri sau workshop-uri tehnice adresate doar anumitor categorii de utilizatori și la care pot participa doar cei care &icirc;ndeplinesc anumite criterii de specialitate).<br />Date angajare</p>
                <p>Sunt date specifice colectate numai &icirc;n relație cu angajații sau colaboratorii noștri &icirc;n scopul &icirc;ntocmirii și semnării contractului de muncă/colaborare și a prevederilor legale &icirc;n domeniul muncii.</p>
                <p><br />Date tehnice online</p>
                <p>Site-urile moderne colectează automat o serie de informații de tip cookie-uri și informații din traficul de server. Atunci c&acirc;nd un utilizator vizitează un site web, sunt comunicate automat o serie de informații tehnice precum adresa IP, ora vizitei, website-ul sursă dacă a fost accesat un link cu trimitere pe site-ul nostru. eu-truckers.com, ca și alte website-uri, &icirc;nregistrează automat aceste informații ca parte a rutinelor sale de software, pentru rațiuni de securitate (protecție la atacuri software) și pentru a urmări traficul &icirc;nregistrat pe website și paginile cele mai accesate de către utilizatorii săi, pentru a putea personaliza conținutul afișat.<br />De reținut: cookie-urile nu solicită informații cu caracter personal si nu identifică personal utilizatorii de internet.<br />Cookies și blocarea lor</p>
                <p>Un &bdquo;cookie&rdquo; este un fișier de mici dimensiuni, format din litere și numere, care va fi stocat pe computerul, terminalul mobil sau alte echipamente ale unui utilizator de pe care se accesează Internetul, și este complet &ldquo;pasiv&rdquo; (nu conţine programe software, viruşi sau spyware şi nu poate accesa informaţiile de pe hard driverul utilizatorului).<br />Acest website folosește cookie-uri proprii și de la terți pentru a furniza vizitatorilor o experiență mult mai bună de navigare și servicii adaptate nevoilor și interesului fiecăruia. De exemplu, cookie-urile ajută la personalizarea anumitor setări precum limba &icirc;n care este vizualizat un site, moneda &icirc;n care se exprimă anumite prețuri sau tarife, păstrarea opțiunilor pentru diverse produse &icirc;n coșul de cumpărături.<br />Majoritatea browser-elor sunt setate să accepte cookie-uri. Indiferent de browser-ul utilizat, utilizatorul poate seta browser-ul astfel &icirc;nc&acirc;t să fie informat despre cookie-urile primite ori să refuze cu totul acceptarea oricărui cookie. Din motive strict tehnice, dezactivarea și refuzul de a primi cookie-uri pot face anumite site-uri impracticabile sau dificil de vizitat și folosit.<br />Dacă vă doriți să blocați primirea de cookies, accesați meniul Setări sau Opțiuni ori Preferințe din browser-ul pe care &icirc;l folosiți, refuz&acirc;nd astfel utilizarea cookie-urilor.<br />Google Analytics: Acest site utilizează Google Analytics, un serviciu de analiză a traficului web furnizat de Google, Inc.. Google Analytics folosește cookies necesare pentru a analiză modul &icirc;n care utilizatorii utilizează site-ul nostru. Informațiile generate de cookie despre utilizarea site-ului web sunt transmise și stocate de Google pe serverele din Europa și Statele Unite. Google va utiliza aceste informații &icirc;n scopul evaluării utilizării site-ului web, al realizării rapoartelor privind traficul pe site și &icirc;n furnizarea altor servicii legate de utilizarea internetului. Google poate, de asemenea, să transfere aceste informații unor terțe părți, &icirc;n cazul &icirc;n care acest lucru este cerut prin lege sau &icirc;n cazul &icirc;n care aceste terțe părți procesează informațiile &icirc;n numele Google. Prin utilizarea site-ului nostru, ești de acord cu prelucrarea datelor tale de către Google &icirc;n modul și &icirc;n scopurile menționate mai sus.</p>
                <p>Scopuri Colectare Date<br />&Icirc;n sens larg, colectăm date personale cu următoarele scopuri:</p>
                <p>promovarea serviciilor oferite prin site-ul eu-truckers.com<br />&icirc;n vederea derulării proiectelor de recrutare și gestionare a contractelor de muncă pentru angajații ori colaboratorii noștri, sau, contractual, pentru clienți;<br />Destinatari &ndash; cine are acces la datele personale colectate<br />Suntem unicul destinatar al datelor personale colectate. Singura excepție o reprezintă cookie-urile care pot proveni și de la alți furnizori (de exemplu Google Analytics).</p>
                <p>Eu-truckers.com nu vinde și nu pune la dispoziția terților datele cu caracter personal pe care le prelucrează.</p>
                <p>Date cu caracter personal se pot transmite autorităților publice, &icirc;n temeiul legii, &icirc;n cazul unui ordin judecătoresc sau pentru a ne conforma altor cerințe legale sau de reglementare oficiale.</p>
                <p>Temeiul Legal privind prelucrarea datelor personale<br />&Icirc;ntocmirea și Executarea contractelor (art. 6 alin. (1) lit. b și c din Regulamentul (UE) 679/2016)<br />Consimțăm&acirc;ntul persoanelor vizate, fie prin faptul că persoana vizată are inițiativa transmiterii unor date cu caracter personal către noi, de exemplu, &icirc;n cazul contactării societății pe pagina de Contact sau ca urmare a acceptării notificării privind politica de cookies<br />&Icirc;ntocmirea facturilor fiscale<br />&Icirc;n privința datelor colectate automat prin folosirea cookie-urilor sau a altor tehnologii similare, temeiul pentru prelucrare este consimțăm&acirc;ntul. Odată cu accesarea site-ului, și selectarea opțiunii DA/De acord utilizatorii &icirc;și exprimă &icirc;n mod valabil consimțăm&acirc;ntul asupra prelucrării.<br />C&acirc;t timp stocăm datele personale<br />Durata de stocare a datelor depinde de natură interacțiunii cu site-ul și serviciile furnizate.</p>
                <p>&Icirc;n cazul semnării unui contract, datele sunt stocate pe perioada valabilități contractului, c&acirc;t și o perioada după (perioada legală obligatorie) necesară pentru a face dovadă contractului<br />&Icirc;n cazul unor interacțiuni sporadice, &icirc;ntrebări/mesaje diverse, păstram datele 1 an<br />&Icirc;n cazul emiterii unor facturi (cursuri, servicii, etc), suntem obligați de lege să păstram datele financiare pe o perioada de minim 10 ani<br />&Icirc;n cazul contractelor de muncă pentru angajați sau colaboratori, datele se păstrează pe durata reglementată de legislația muncii.<br />Securitatea datelor colectate<br />&Icirc;n conformitate cu stadiul actual al tehnologiei, am implementat măsuri tehnice și organizatorice adecvate pentru asigurarea securității datelor cu caracter personal (criptare, restricționare acces neautorizat).</p>
                <p>&Icirc;n ceea ce privește datele colectate online, acestea sunt criptate și protejate automat prin intermediul protocolului HTTPS.</p>
                <p>Modificări și Actualizări ale Politicii de protecție a datelor cu caracter personal<br />Eu-truckers.com &icirc;și rezervă dreptul de a modifica Politica de Protecție a Datelor cu Caracter Personal oric&acirc;nd este necesar. Dacă există modificări semnificative, acestea se vor reflecta &icirc;n timp util &icirc;n versiunea actualizată a acestui document.</p>
                <p>Puteți reveni periodic la această politică de protecție a datelor cu caracter personal pentru a fi informat privind cea mai nouă versiune a acestui document.</p>
                <p>Contact și exercitare drepturi<br />Pentru exercitarea drepturilor de mai sus, utilizatorii ne pot contacta la candidati@eu-truckers.com</p>
                <p>Vom &icirc;ncerca să răspundem solicitărilor &icirc;n termen de 30 de zile sau mai repede, &icirc;n funcție de diferite aspecte tehnice ale solicitării, complexitatea cererii sau alte aspecte precum numărul mare de cereri primite sau imposibilitatea de a identifica utilizatorul &icirc;ntr-un termen util.</p>
            </div>
        </div>
    </div>
</section>






<?php include "includes/parts/footer.php"; 
?>
